### ISSUE TITLE
wrong suggestion when string requested on hash and keys are symbols

### ISSUE THREAD

**Issue by localhostdotdev** [ruby/did_you_mean#121]
e.g.

```ruby
>> { aaa_a: 1, aaa_b: 1 }.fetch("aaa_b")
KeyError (key not found: "aaa_b")
Did you mean?  :aaa_a
```

ruby -v: `ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]`

verified with:

```ruby
DidYouMean::SpellChecker.new(dictionary: [:aaa_a, :aaa_b]).correct("aaa_a")
=> [:aaa_b]
```

**Comment by yuki24** [comment]
This is a very tricky case where the class of the key could make the accuracy worse, but yes it should suggest `:aaa_b` instead of `:aaa_a`.
