### ISSUE TITLE
Issues with the did_you_mean deprecation warning

### ISSUE THREAD

**Issue by eregon** [ruby/did_you_mean#171]
I've noticed https://github.com/rubygems/rubygems/issues/5234 as well.

I think there are multiple improvements here:
* The warning should show the caller, otherwise it's hard to know which gem is causing it (`warn msg, uplevel: 1` does that).
* Since it's a deprecation warning it would be great to only show it when `Warning[:deprecated]` Of course that only works on Ruby 2.7+, on other versions probably better to show only `if $VERBOSE`.
* (`warn msg, category: :deprecated` would also work but needs Ruby 3+)

**Comment by eregon** [comment]
There is also the question whether it's worth at all to warn for this, given the current code handles it just fine by [forwarding to the new method](https://github.com/ruby/did_you_mean/blob/0034f8b304aa3bd7c382b92932a0b8fd95185aad/lib/did_you_mean.rb#L117-L137).
Having 2 public APIs for the same thing is not ideal, so the warning makes sense for that, but OTOH asking various usages to update just for Ractor support which is likely not used (and would work fine with the old way due to the forwarding) is not ideal either.

**Comment by eregon** [comment]
I noticed the `deprecate_constant :SPELL_CHECKERS` so we would get a location if `Warning[:deprecated]` (non-default on 2.7.2+). So maybe no need to show the caller if we only warn when `Warning[:deprecated]`.

**Comment by morgoth** [comment]
@eregon do you know if it's somehow possible to find the offensive gem currently in the codebase? I'm getting it in the Rails app and I have no idea how to find it, to report it or fix

**Comment by eregon** [comment]
Maybe running after `export RUBYOPT=-W:deprecated` helps to find out.

**Comment by yuki24** [comment]
Thank you all for all the insights and recommendations. Really appreciate the time you all have taken for the conversation here. With all that said, I don't think this is an issue today. I know people (including me) have run into an awkward situation, but this is a problem time will (or possibly have already solved) solve. If anyone runs into this issue. please refer to https://github.com/rubygems/rubygems/issues/5234 for how to fix it.
