### ISSUE TITLE
Wrong suggestion when passing correct spelling

### ISSUE THREAD

**Issue by jeet-codecimal** [ruby/did_you_mean#187]
Getting wrong suggestions while passing correct spelled word.

![Screenshot-from-2023-07-10-12-27-20](https://github.com/ruby/did_you_mean/assets/82138480/d5e22966-54d4-4aa3-a34a-5f03556d92fe)

```
dictionary = ["kidney", 'kidneys']
spell_checker = DidYouMean::SpellChecker.new(dictionary: dictionary)
n_name = spell_checker.correct('kidney')

Output
["kidneys"] 
```

Expected results should be ["kidney"]

**Comment by makenowjust** [comment]
It seems expected behavior to me. See the [test case](https://github.com/ruby/did_you_mean/blob/3305559e6c3c0e38fb4c1bb652ba5aa069800462/test/test_spell_checker.rb#L13) for instance.

`DidYouMean::SpellChecker#correct` runs with considering the argument as misspelled even if the given word is contained in its dictionary.

**Comment by jeet-codecimal** [comment]
I have a word "chronnic kidney disease", which is not correct (it should be 'chronic kidney disease'). I am breaking this word in 3 and checking each word separately for misspelled case. I am getting proper result for "chronnic" but not for other 2. I don't have any issue if other 2 which are correct words do not give results at all but in it gives other results like "kidneys" in case of "kidney" and "dishes" is case of "disease".

Is there any solution present in did you mean to handle this use case ?

**Comment by makenowjust** [comment]
You can use `dictionary.include?(word)`. If `dictionary.include?(word)` returns `true`, it is unnecessary to call `SpellChecker#correct` because the spelling of `word` is correct.

**Comment by jeet-codecimal** [comment]
Thank you for this suggestion.
