### ISSUE TITLE
"did you mean more speed?"

### ISSUE THREAD

**Issue by rubyFeedback** [ruby/did_you_mean#190]
So the did-you-mean gem was a big success.

How about a kind of "add on" to it? Kind of like a variant that recommends to
people where to save time; where to make the ruby code execute faster. A bit
like a combination between did-you-mean as well as rubocop, just with a
focus on performance.

Anyway. That's just a rough idea. If anyone is ever bored and has too much
time then this could be interesting - making ruby code that exists in the
wild faster, and helper tools for that, such as did-you-mean-more-speed.

**Comment by yuki24** [comment]
Thanks for your suggestion. I think there is already a project more suitable to what you are proposing here: https://github.com/rubocop/rubocop-performance.

Given that it already exists, I don't see the need of doing it as part of `did_you_mean`.
